version: 2
registries:
  git-github-com:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.GIT_GITHUB_COM_PASSWORD}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: US/Eastern
  open-pull-requests-limit: 10
  assignees:
  - sweir27
  ignore:
  - dependency-name: react
    versions:
    - 17.0.1
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: react-redux
    versions:
    - 7.2.2
  - dependency-name: babel-plugin-module-resolver
    versions:
    - 4.0.0
  registries:
  - git-github-com
