git-remote: git@github.com:artsy/positron.git
project-name: positron
pre-build: export COMMIT_HASH=$(git rev-parse --short HEAD)
pre-deploy: yarn publish-assets
hokusai-required-version: ">=0.5.8"
template-config-files:
  - s3://artsy-citadel/k8s/hokusai-vars.yml
