version: "2"
volumes:
  positron-mongodb-data-volume:
services:
  positron:
{% include 'templates/docker-compose-service.yml.j2' %}
    command: ["yarn", "dev"]
    environment:
      - MONGOHQ_URL=mongodb://positron-mongodb:27017/positron
      - ELASTICSEARCH_URL=http://positron-elasticsearch:9200
      # SALT is an oss value. The '$' is escaped.
      - SALT=$$2a$$10$$PJrPMBadu1NPdmnshBgFbe
    env_file:
      - ../.env.shared
      - ../.env
    depends_on:
      - positron-mongodb
      - positron-elasticsearch
    ports:
      - 3005:3005
  positron-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9300:9300
      - 9200:9200
  positron-mongodb:
    image: mongo:4.4
    command: ["--quiet", "--nojournal"]
    ports:
      - 27017:27017
    volumes:
      - positron-mongodb-data-volume:/data/db
