version: "2"
services:
  positron:
{% include 'templates/docker-compose-service.yml.j2' %}
    command: ["yarn", "dev"]
    env_file:
      - ../.env.shared
      - ../.env
    depends_on:
      - positron-mongodb
      - positron-elasticsearch
    network_mode: "host"
  positron-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    network_mode: "host"
  positron-mongodb:
    image: mongo:4.0
    command: ["--storageEngine=mmapv1", "--quiet", "--nojournal"]
    network_mode: "host"
