version: "2"
services:
  positron:
    command: ["yarn", "test"]
{% include 'templates/docker-compose-service.yml.j2' %}
    environment:
      - CI=true
      - ELASTICSEARCH_URL=http://positron-elasticsearch:9200
      - MONGOHQ_URL=mongodb://positron-mongodb:27017/positron-test
      # SALT is an oss value. The '$' is escaped.
      - SALT=$$2a$$10$$PJrPMBadu1NPdmnshBgFbe
    env_file: ../.env.test
    depends_on:
      - positron-mongodb
      - positron-elasticsearch
  positron-elasticsearch:
    image: elasticsearch:7.17.27
    user: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ingest.geoip.downloader.enabled=false"
      - "_JAVA_OPTIONS=-XX:UseSVE=0"
    ports:
      - "9200:9200"
  positron-mongodb:
    image: mongo:6.0.16
    ports:
      - "27017:27017"
    command: ["--quiet", "--nojournal"]
