version: "2"
services:
  positron:
    command: ["yarn", "test"]
{% include 'templates/docker-compose-service.yml.j2' %}
    environment:
      - CI=true
      - ELASTICSEARCH_URL=http://positron-elasticsearch:9200
      - ELASTICSEARCH_INDEX_SUFFIX=test
      - MONGOHQ_URL=mongodb://positron-mongodb:27017/positron-test
      # SALT is an oss value. The '$' is escaped.
      - SALT=$$2a$$10$$PJrPMBadu1NPdmnshBgFbe
    env_file: ../.env.test
    depends_on:
      - positron-mongodb
      - positron-elasticsearch
  positron-elasticsearch:
    image: opensearchproject/opensearch:1.3.20
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  positron-mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    command: ["--quiet"]
