version: "2"
services:
  positron:
    command: ["yarn", "test"]
{% include 'templates/docker-compose-service.yml.j2' %}
    environment:
      - CI=true
      - ELASTICSEARCH_URL=http://positron-elasticsearch:9200
      - MONGOHQ_URL=mongodb://positron-mongodb:27017/positron-test
    env_file: ../.env.test
    depends_on:
      - positron-mongodb
      - positron-elasticsearch
  positron-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  positron-mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"
    command: ["--storageEngine=mmapv1", "--quiet", "--nojournal"]
