version: "2"
services:
  positron:
    command: ["yarn", "test"]
    tty: true
{% include 'templates/docker-compose-service.yml.j2' %}
    environment:
      - CI=true
      - MONGOHQ_URL=mongodb://positron-mongodb:27017/positron-test
      # SALT is an oss value. The '$' is escaped.
      - SALT=$$2a$$10$$PJrPMBadu1NPdmnshBgFbe
    env_file: ../.env.test
    depends_on:
      positron-mongodb:
        condition: service_healthy
      positron-opensearch:
        condition: service_started
  positron-opensearch:
    image: opensearchproject/opensearch:2.17.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  positron-mongodb:
    image: mongo:7.0
    command: ["--quiet"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5
