artists = ['banksy',
'andy warhol',
'jean michel basquiat',
'marina abramovic',
'keith haring',
'damien hirst',
'jeff koons',
'roy lichtenstein',
'ai weiwei',
'takashi murakami',
'wassily kandinsky',
'robert mapplethorpe',
'alexander calder',
'cindy sherman',
'sebastiao salgado',
'chuck close',
'yayoi kusama',
'david lachapelle',
'anish kapoor',
'robert rauschenberg',
'fernando botero',
'joan miro',
'willem de kooning',
'tracey emin',
'gerhard richter',
'jock sturges',
'wayne thiebaud',
'olafur eliasson',
'shepard fairey',
'jenny saville',
'barbara kruger',
'zaria forman',
'andreas gursky',
'william eggleston',
'frank stella',
'nobuyoshi araki',
'gregory crewdson',
'alec monopoly',
'louise bourgeois',
'mr brainwash',
'vik muniz',
'sol lewitt',
'cai guo qiang',
'ed ruscha',
'kehinde wiley',
'egon schiele',
'jim dine',
'anselm kiefer',
'donald judd',
'hannah hoch',
'kara walker',
'franz kline',
'richard serra',
'ryan mcginley',
'jenny holzer',
'richard prince',
'helen frankenthaler',
'robert frank',
'alex katz',
'yves klein',
'antony gormley',
'jean arp',
'cy twombly',
'marc quinn',
'audrey kawasaki',
'william kentridge',
'kathe kollwitz',
'kiki smith',
'blek le rat',
'paul strand',
'hiroshi sugimoto',
'victor vasarely',
'yoshitomo nara',
'james rosenquist',
'andre derain',
'dustin yellin',
'john currin',
'richard diebenkorn',
'robert motherwell',
'robert longo',
'tom wesselmann',
'noah davis',
'pablo picasso',
'hans hofmann',
'shirin neshat',
'retna',
'hans bellmer',
'vanessa beecroft',
'david alfaro siqueiros',
'henri matisse',
'thomas ruff',
'bruce nauman',
'rachel whiteread',
'li hongbo',
'judy chicago',
'elizabeth peyton',
'sterling ruby',
'malcolm t liepke',
'cecily brown',
'ron english',
'jr',
'richard estes',
'salvador dali',
'sally mann',
'christopher wool',
'bridget riley',
'john baldessari',
'ellsworth kelly',
'niki de saint phalle',
'henry moore',
'dan flavin',
'richard mosse',
'george condo',
'theaster gates',
'christo',
'zanele muholi',
'nicola samori',
'julian opie',
'pieter hugo',
'riusuke fukahori',
'alyssa monks',
'jean paul goude',
'lorna simpson',
'michael carson',
'sister mary corita kent',
'beth cavener',
'yasumasa morimura',
'jose parla',
'francesco clemente',
'dan colen',
'marilyn minter',
'andrew salgado',
'kerry james marshall',
'yue minjun',
'jill greenberg',
'danh vo',
'emil nolde',
'adrian ghenie',
'rene magritte',
'lucio fontana',
'manfred mohr',
'candida hofer',
'stanley whitney',
'wayne white',
'wolf kahn',
'massimo vitali',
'richard hamilton',
'kenny scharf',
'gunther forg',
'james turrell',
'clare e rojas',
'do ho suh',
'tauba auerbach',
'gary baseman',
'olga kisseleva',
'marcel duchamp',
'xu bing xu bing',
'daniel arsham',
'richard misrach',
'sarah morris',
'john chamberlain',
'julie mehretu',
'daido moriyama',
'tara donovan',
'agnes martin',
'francis newton souza',
'dana schutz',
'wes lang',
'louise nevelson',
'petra cortright',
'eric fischl',
'sonia delaunay',
'richard phillips',
'conor harrington',
'erwin olaf',
'jean auguste dominique ingres',
'philip lorca dicorcia',
'milton avery',
'jesus rafael soto',
'rinko kawauchi',
'barry mcgee',
'hellen van meene',
'harland miller',
'jean dubuffet',
'mariko mori',
'audrey flack',
'josef albers',
'josh agle shag',
'mickalene thomas',
'alex prager',
'alice neel',
'annie leibovitz',
'jeremy geddes',
'kwangho shin',
'esao andrews',
'russell young',
'ansel adams',
'jasper johns',
'ronald davis',
'zhang xiaogang',
'ralph goings',
'ugo rondinone',
'alfredo jaar',
'david hammons',
'janet fish',
'antony micallef',
'giuseppe penone',
'hebru brantley',
'helmut newton',
'lourdes sanchez',
'nicole eisenman',
'walton ford',
'sheila hicks',
'roberto matta',
'jason martin',
'marcel dzama',
'maggie taylor',
'kaws',
'mel bochner',
'mel ramos',
'mark tansey',
'jung lee',
'invader',
'eddie martinez',
'douglas gordon',
'alex israel',
'tali lennox',
'zeng fanzhi',
'bjarne melgaard',
'naum gabo',
'carrie mae weems',
'raoul dufy',
'mark tobey',
'sebastian errazuriz',
'jaehyo lee',
'damian ortega',
'rudolf stingel',
'lucien smith',
'kazuo shiraga',
'adrian villar rojas',
'marco grassi',
'peter halley',
'korakrit arunanondchai',
'mark rothko',
'philip pearlstein',
'mark grotjahn',
'nan goldin',
'larry rivers',
'alicja kwade',
'holton rower',
'jimmie durham',
'joe andoe',
'katsu',
'ivar wigan',
'jonas wood',
'os gemeos',
'hank willis thomas',
'lionel smit',
'zhang huan',
'laura jordan',
'david hockney',
'james nares',
'eloy morales',
'wade guyton',
'sam francis',
'urs fischer',
'yago hortal',
'piet mondrian',
'aaron siskind',
'larry bell',
'geoff mcfetridge',
'ray caesar',
'stephen mackey',
'takuma nakahira',
'katharina grosse',
'sam gilliam',
'cheri samba',
'lynette yiadom boakye',
'hendrik kerstens',
'haroshi',
'sarah anne johnson',
'katherine bernhardt',
'anni albers',
'ross bleckner',
'mark flood',
'jeremy lipking',
'yigal ozeri',
'julian schnabel',
'brian kokoska',
'camille rose garcia',
'the haas brothers',
'alex kanevsky',
'rex ray',
'bharti kher',
'natalie frank',
'marc chagall',
'jonathan meese',
'hunt slonem',
'ron nagle',
'donatello',
'rachel howard',
'bruno walpoth',
'glenn brown',
'francesco vezzoli',
'imi knoebel',
'jean pierre hebert',
'tim hawkinson',
'joseph stella',
'betty woodman',
'kohei nawa',
'peter doig',
'david salle',
'elger esser',
'martin kippenberger',
'jack pierson',
'tetsuya ishida',
'julio le parc',
'keltie ferris',
'tony lewis',
'matthew brandt',
'edouard vuillard',
'ian francis',
'peter hujar',
'genieve figgis',
'ori gersht',
'jeff soto',
'paul jenkins',
'michael kagan',
'otto piene',
'julie blackmon',
'waqas khan',
'lee ufan',
'barbara kasten',
'jun kaneko',
'domingo zapata',
'kenneth noland',
'mimmo paladino',
'cleon peterson',
'joel shapiro',
'cerith wyn evans',
'ryan mcginness',
'sam falls',
'joaquin torres garcia',
'igor mitoraj',
'robert indiana',
'todd james',
'anthony goicolea',
'bruce conner',
'franz ackermann',
'allison schulnik',
'francois morellet',
'philippe parreno',
'john mccracken',
'alex da corte',
'john de andrea',
'zaha hadid',
'ramiro gomez',
'patrick hughes',
'zao wou ki zhao wu ji',
'chantal joffe',
'valerie belin',
'jeffrey milstein',
'andrea kowch',
'sherie franssen',
'tom friedman',
'judy pfaff',
'hung liu',
'larry poons',
'robert mangold',
'richard aldrich',
'kerstin bratsch',
'jaume plensa',
'yoshitaka amano',
'jitka hanzlova',
'idris khan',
'pat steir',
'eric zener',
'matthias weischer',
'donald sultan',
'william wegman',
'mike kelley',
'wang guangyi',
'david lynch',
'charline von heyl',
'lynn chadwick',
'brian calvin',
'alexander archipenko',
'know hope',
'cory arcangel',
'chris johanson',
'heimo zobernig',
'peter alexander',
'ryan gander',
'roberto bernardi',
'philip taaffe',
'syed haider raza',
'oleg dou',
'adam wallacavage',
'max ernst',
'choi jeong hwa',
'ron hicks',
'george woodman',
'olaf breuning',
'xu zhen',
'yang fudong',
'dennis oppenheim',
'kelly reemtsen',
'betye saar',
'hans peter feldmann',
'raymond pettibon',
'nick gentry',
'jonathan borofsky',
'john mcallister',
'jorinde voigt',
'aron wiesenfeld',
'donald baechler',
'tim knowles',
'helena almeida',
'torey thornton',
'tim eitel',
'stanley casselman',
'laura lancaster',
'aj fosik',
'keiichi tanaami',
'grace hartigan',
'keith tyson',
'jee young lee',
'jonathan yeo',
'hamish fulton',
'pose',
'chiharu shiota',
'kiki kogelnik',
'jack whitten',
'miya ando',
'richard anuszkiewicz',
'daniel pitin',
'david kracov',
'makoto fujimura',
'richard pettibone',
'diana al hadid',
'will cotton',
'manolo valdes',
'vija celmins',
'piotr uklanski',
'herakut',
'david reed',
'charles avery',
'kasper sonne',
'leon kossoff',
'keith sonnier',
'aaron young',
'sara vanderbeek',
'chris succo',
'jacob hashimoto',
'kwang young chun',
'harmony korine',
'sigmar polke',
'marta minujin',
'rackstraw downes',
'peter anton',
'tal r',
'jim joe',
'alexander tovborg',
'matthew cusick',
'leila jeffreys',
'lee krasner',
'harold ancart',
'daniel joseph martinez',
'taner ceylan',
'mario testino',
'philip guston',
'ar penck',
'michael lin',
'marco perego saldana',
'dean levin',
'martin wehmer',
'olga de amaral',
'leonora carrington',
'fred tomaselli',
'paige powell',
'tomoo gokita',
'kim dorland',
'doze green',
'brett amory',
'manuel ocampo',
'inez and vinoodh',
'dain',
'paul cadmus',
'hannah perry',
'robert cottingham',
'ettore spalletti',
'paul wackers',
'claudio bravo',
'noemie goudal',
'aaron curry',
'esteban vicente',
'theodoros stamos',
'cracking art group',
'kelsey brookes',
'nick cave',
'sage vaughn',
'mark wagner',
'al held',
'justin mortimer',
'clara peeters',
'jim lambie',
'joe black',
'robert mars',
'joseph kosuth',
'kudzanai chiurai',
'andrej dubravsky',
'sharon core',
'deborah butterfield',
'u ram choe',
'robert therrien',
'david bates',
'katherine bradford',
'evol',
'james marshall dalek',
'claudio parmiggiani',
'terry adkins',
'joseph nechvatal',
'luke diiorio',
'kim keever',
'tomory dodge',
'jake and dinos chapman',
'cali thornhill dewitt',
'jose alvarez dopa',
'anselm reyle',
'romare bearden',
'julie cockburn',
'gilbert garcin',
'chris burden',
'sue williams',
'gajin fujita',
'norman bluhm',
'daniel sprick',
'darren almond',
'zhuang hong yi',
'paulina olowska',
'eric white',
'dan mccarthy',
'abdur rahman chughtai',
'thomas grunfeld',
'takis',
'brice marden',
'tony fitzpatrick',
'edward burtynsky',
'teresita fernandez',
'karl maughan',
'kadar brock',
'peter beard',
'julio larraz',
'jeff zimmerman',
'gideon rubin',
'daniel heidkamp',
'meredith pardue',
'john crash matos',
'tilo baumgartel',
'david ostrowski',
'tracey rose',
'aleksandra domanovic',
'davide balula',
'graham collins',
'annie morris',
'zio ziegler',
'larry clark',
'floris neususs',
'john wesley',
'ibrahim mahama',
'david wiseman',
'dan witz',
'enoc perez',
'esko mannikko',
'liu xiaodong',
'ben eine',
'todo ramon',
'jose davila',
'graham wilson',
'jem southam',
'simen johan',
'abraham palatnik',
'n dash',
'awol erizku',
'dan christensen',
'jacob kassay',
'jarek puczel',
'raphael mazzucco',
'maya hayuk',
'pierre gonnord',
'leonardo drew',
'kris martin',
'robbert flick',
'paul noble',
'sanya kantarovsky',
'martin mull',
'nick darmstaedter',
'patrick wilson',
'angela bulloch',
'julien marinetti',
'kurt schwitters',
'mary weatherford',
'guillermo kuitca',
'fulvio di piazza',
'america martin',
'marlene dumas',
'michael gregory',
'raymond saunders',
'robin eley',
'henry wessel',
'elizabeth neel',
'hedda sterne',
'julie heffernan',
'alain biltereyst',
'cal lane',
'thomas campbell',
'ibrahim el salahi',
'zhu jinshi',
'israel lund',
'deana lawson',
'david shrigley',
'bradley theodore',
'liam everett',
'leo gabin',
'todd hido',
'mathias kiss',
'secundino hernandez',
'kenneth josephson',
'mark bradford',
'jen stark',
'andrew moore',
'lawrence carroll',
'matt mullican',
'nick van woert',
'john copeland',
'eko nugroho',
'wallace berman',
'alicia mccarthy',
'justin adian',
'faig ahmed',
'haley mellin',
'emi anrakuji',
'myoung ho lee',
'richard mayhew',
'markus linnenbrink',
'natvar bhavsar',
'thilo heinzmann',
'james jean',
'serena mitnik miller',
'leif ritchey',
'sean scully',
'agostino bonalumi',
'nathaniel mary quinn',
'atul dodiya',
'paulette tavormina',
'ethan murrow',
'sam moyer',
'claude lalanne',
'hubert de lartigue',
'michael eastman',
'rafael barrios',
'ding yi',
'alexander tinei',
'ken knight',
'ysabel lemay',
'richard lindner',
'sarah crowner',
'sadamasa motonaga',
'wyatt kahn',
'david nash',
'yang yongliang yang yong liang',
'takuro kuwata sang tian zhuo lang',
'brendan lynch',
'david drebin',
'varda caivano',
'patricia treib',
'barkley l hendricks',
'andres serrano',
'matthew pillsbury',
'alex hubbard',
'ted gahl',
'kathy butterly',
'zane lewis',
'katrin fridriks',
'julian stanczak',
'chen wenling',
'nathan sawaya',
'marco breuer',
'elizabeth catlett',
'david gilhooly',
'mark hagen',
'desire obtain cherish',
'fos',
'andy denzler',
'klara kristalova',
'alison rossiter',
'laddie john dill',
'jonathan gardner',
'rose wylie',
'samantha keely smith',
'ella kruglyanskaya',
'betty tompkins',
'elliott puckette',
'cecil touchon',
'seon ghi bahk',
'ikeda manabu',
'donald roller wilson',
'alan charlton',
'danny galieote',
'marjorie strider',
'ian davenport',
'kate steciw',
'ronald ventura',
'sebastian black',
'li lihong',
'miaz brothers',
'susan hauptman',
'kim joon',
'massimo listri',
'charles arnoldi',
'max gimblett',
'carroll cloar',
'lucas arruda',
'grear patterson',
'rob tucker',
'nicholas hlobo',
'satoshi ohno',
'jeff wall',
'martin soto climent',
'markus brunetti',
'ethan cook',
'serban savu',
'jared madere',
'ahmad zakii anwar',
'pamela rosenkranz',
'mauro perucchetti',
'gao xingjian gao xing jian',
'stephen wilkes',
'louise fishman',
'will adler',
'eloise hawser',
'anthony pearson',
'josh reames',
'sybil andrews',
'razvan boar',
'zhao zhao',
'travess smalley',
'vanessa german',
'garth weiser',
'gregory halili',
'alex becerra',
'john zinsser',
'john mellencamp',
'bernard aubertin',
'laurent chehere',
'risk',
'liu dan',
'tom lieber',
'chloe early',
'he xiangyu',
'hyuro',
'mel brigg',
'conor backman',
'qin feng',
'richard hambleton',
'david mach',
'claire fontaine',
'robert montgomery',
'paolo scheggi',
'kim cogan',
'richard colman',
'jose basso',
'colin chillag',
'anthony lister',
'richard butler',
'jerome lagarrigue',
'luciano ventrone',
'judith supine',
'gianfranco baruchello',
'charles gaines',
'jon rafman',
'lesley vance',
'john waters',
'gu wenda',
'ed templeton',
'eva kotatkova',
'nancy rubins',
'howard hodgkin',
'imran qureshi',
'despina stokou',
'thornton dial',
'stelios faitakis',
'ernesto caivano',
'li huayi',
'mattia bonetti',
'brent wadden',
'guy yanai',
'sam friedman',
'joe reihsen',
'billy sullivan',
'oscar bluemner',
'eduardo berliner',
'william bailey',
'christian boltanski',
'eric blum',
'jim thorell',
'hugh scott douglas',
'liu kuo sung liu guosong',
'margo wolowiec',
'paul dibble',
'math bass',
'carl melegari',
'ben schumacher',
'olive ayhens',
'jack greer',
'murray fredericks',
'aaron garber maikovska',
'carlos cruz diez',
'brad reuben kunkle',
'f scott hess',
'maira kalman',
'simryn gill',
'michael staniak',
'kishio suga jian mu zhi xiong',
'evan hecox',
'william beckman',
'ramazan bayrakoglu',
'jon pestoni',
'maria taniguchi',
'wang dongling',
'thomas joshua cooper',
'mcarthur binion',
'marco mazzoni',
'zander blom',
'roy de forest',
'jesse wine',
'bast',
'will boone',
'mircea suciu',
'beverly mciver',
'dasha shishkin',
'russell james',
'michiel ceulers',
'takahiro hirabayashi',
'deborah oropallo',
'will kurtz',
'jane corrigan',
'robert davis',
'don brown',
'margaret kilgallen',
'kiluanji kia henda',
'ola kolehmainen',
'attasit pokpong',
'kris kuksi',
'james verbicky',
'phil shaw',
'saul leiter',
'joshua jensen nagle',
'eduardo t basualdo',
'louisa matthiasdottir',
'louie cordero',
'robert kelly',
'markus dobeli',
'jess fuller',
'annie lapin',
'brenda fajardo',
'lisa brice',
'margo selski',
'philip and kelvin laverne',
'edwige fouvry',
'liu di',
'geraldine javier',
'ong kim seng',
'david diao',
'kwangho lee',
'nicolas africano',
'dashiell manley',
'judy kensley mckie',
'wolfgang tillmans',
'erik desmazieres',
'teodora axente',
'cody hoyt',
'anna hepler',
'maria berrio',
'gabriele de santis',
'pierre auguste renoir',
'tim bavington',
'ravi zupa',
'moshekwa langa',
'luc leestemaker',
'penny siopis',
't dot r ericsson',
'ran ortner',
'luis tomasello',
'farideh lashai',
'huger foote',
'nathan hylden',
'kate macdowell',
'sarah dwyer',
'rob pruitt',
'isca greenfield sanders',
'blair thurman',
'ran hwang',
'cary leibowitz slash candyass',
'chris jordan',
'sophie cape',
'davide balliano',
'zak prekop',
'sofia leiby',
'philipp roessle',
'jennifer packer',
'roa',
'russell tyler',
'rosy keyser',
'kaari upson',
'abigail reynolds',
'john tsombikos',
'james havard',
'ewa bathelier',
'katsuyo aoki',
'abbey mcculloch',
'zheng chongbin',
'jane waterous',
'louis eisner',
'kim dong yoo',
'jannis varelas',
'raymond han',
'oliver marsden',
'alex ruthner',
'jim drain',
'jacob el hanani',
'victor matthews',
'monique van genderen',
'bruce davenport jr',
'nick farhi',
'matthew chambers',
'anna bjerger',
'richard lytle',
'charlie billingham',
'stephane dessaint',
'neil raitt',
'michael bevilacqua',
'michael muir',
'ketuta alexi meskhishvili',
'miles aldridge',
'ron kingswood',
'john singer sargent',
'ron bolt',
'jonathan hernandez',
'zhang ding',
'gerd rothmann',
'eric freeman',
'zach bruder',
'zachary leener',
'revok',
'claude monet',
'matt mcclune',
'adrian schiess',
'nick aguayo',
'paco pomet',
'fujikasa satoko',
'tracy silva barbosa',
'dragica carlin',
'john sonsini',
'ken strong',
'sohyun bae',
'eric forstmann',
'lance de los reyes',
'eduardo gil',
'anurendra jegadeva']